version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jatboy/project-x:backend-latest
    ports:
      - "8080:8080"
    env_file: 
      - ./backend/.env  
    environment:
      NODE_ENV: production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./project_x_frontend
      dockerfile: Dockerfile
    image: jatboy/project-x:frontend-latest
    ports:
      - "3000:80"


