services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jatboy/project-x:backend-latest
    env_file: 
      - ./backend/.env  
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./project_x_frontend
      dockerfile: Dockerfile
    image: jatboy/project-x:frontend-latest

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Directory to hold your SSL certificates
    depends_on:
      - frontend
      - backend
