
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jatboy/project-x:backend-latest
    ports:
      - "8080:8080"
    env_file: 
      - ./backend/.env  
    environment:
      NODE_ENV: production

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: jatboy/project-x:nginx-latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always



