version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jatboy/project-x:backend-latest
    ports:
      - "8080:8080"
    env_file: 
      - ./backend/.env  
    environment:
      NODE_ENV: production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./project_x_frontend
      dockerfile: Dockerfile
    image: jatboy/project-x:frontend-latest
    ports:
      - "3000:80"

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount the SSL certificates
    depends_on:
      - frontend
      - backend    


