name: project-x-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setting up Docker
      uses: docker/setup-buildx-action@v2

    - name: Logging into Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Creating .env file
      run: echo "DB_URI=${{ secrets.DB_URI }}" > ./backend/.env      

    - name: Building and Starting Services
      run: docker-compose up --build -d
